services:
    # リバースプロキシ兼Webサーバ
    nginx:
        hostname: nginx
        image: nginx:latest
        ports:
            - 8370:8443
        restart: always
        tty: true
        volumes:
            - ./nginx/configs:/etc/nginx/conf.d/
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics:/etc/nginx/static/statics
        networks:
            - frontend
            - backend
    
    # 認証用コンテナ
    auth:
        hostname: auth
        build:
            context: ./auth
            dockerfile: dockerfile
            # target: Release
            target: Develop
        tty: true
        env_file:
            - ./openssl/jwtKeys/private.env
            - ./config/auth.env
        volumes:
            - ./auth/src:/root/src
        restart: always
        depends_on:
            - mysql
        networks:
            - backend
            - database
    
    # アプリケーションコンテナ
    app:
        hostname: app
        build:
            context: ./app
            dockerfile: dockerfile
            target: Release
            # target: Develop
        tty: true
        env_file:
            - ./openssl/jwtKeys/public.env
            - ./config/app.env
        volumes:
            - ./app/src:/root/src
            - ./config/google_cred.json:/google_cred.json:ro
        restart: always
        depends_on:
            - mysql
            - auth
        networks:
            - backend
            - database
    
    # データベース
    mysql:
        hostname: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - dbdata:/var/lib/mysql
            - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./database/script/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - database

volumes:
    dbdata:

networks:
    frontend:
        # 外部からアクセス可能なネットワーク
    database:
        # データベース用のネットワーク
        internal: true
    backend:
        # 内部コンテナ間通信用のネットワーク
        internal: false  # インターネットアクセスを許可